### ISSUE TITLE
OpenPose Models 

### ISSUE THREAD

**Issue by SrinjaySarkar** [eth-ait/GaussianHaircut#2] opened 2024-10-08 11:43 UTC
Thank you very much for open-sourcing the code for your work . I am trying to replicate the results but I am stuck at downloading the OpenPose Models as the server seems to de down like mentioned [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2233) . Could you please share these files through GitLFS or upload it somewhere ?

**Comment by egorzakharov** [comment] 2024-10-10 11:43
I added models to Google Drive. Also, I fixed one of the open pose known complication issues, which was caused by a cmake version discrepancy. Check the latest commit.

**Closed by egorzakharov** 2024-10-10 11:43 UTC
